name       : perl-xml-writer
version    : 0.625
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/J/JO/JOSEPHW/XML-Writer-0.625.tar.gz : e080522c6ce050397af482665f3965a93c5d16f5e81d93f6e2fe98084ed15fbe
license    : Artistic-2.0
component  : programming.perl
summary    : Perl extension for writing XML documents.
description: |
    Perl extension for writing XML documents.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
