name       : perl-xml-writer
version    : '0.900'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/J/JO/JOSEPHW/XML-Writer-0.900.tar.gz : 73c8f5bd3ecf2b350f4adae6d6676d52e08ecc2d7df4a9f089fa68360d400d1f
homepage   : https://metacpan.org/pod/XML::Writer
license    : Artistic-2.0
component  : programming.perl
summary    : XML::Writer - Perl extension for writing XML documents
description: |
    XML::Writer is a helper module for Perl programs that write an XML document. The module handles all escaping for attribute values and character data and constructs different types of markup, such as tags, comments, and processing instructions.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
